Repository FluidSimP/just-simp, pull requests merged in 2022-10, with the labels that each got.

#1 Added base exercise-1 files
  Exercise 1/README.md
  Exercise 1/exercise1.ct
Labels: documentation, hacktoberfest-accepted

#2 added .ct file
  Exercise 1/exercise1.ct
Labels: hacktoberfest-accepted

#3 Added base exercise-2 files
  Exercise 2/README.md
  Exercise 2/exercise2.ct
Labels: documentation, hacktoberfest-accepted

#4 the new file has arrived
  Exercise 2/exercise2.ct
Labels: hacktoberfest-accepted

#5 update readme
  README.md
Labels: enhancement, hacktoberfest-accepted

#6 Su sim
  Exercise 2/README.md
Labels: enhancement, hacktoberfest-accepted

#7 You like my change, don't you?
  Exercise 1/README.md
Labels: hacktoberfest-accepted
